################################  config.py  ####################################
# Author: Sukhendu Sain
# Description: Config file of codebase. Houses different parameters and variables
# Data: 23-Nov-2024
#################################################################################
import os

## @ Files Path ##
ROOT_FILE_PATH = '\\'.join(os.getcwd().split('\\')[:-1])

GPARTS_FILE_PATH = os.path.join(ROOT_FILE_PATH, r"Data&Files\GPARTS Part Measures.xlsx")
WHOLESALE_FILE_PATH = os.path.join(ROOT_FILE_PATH, r"Data&Files\Wholesale JAN_Oct_Parts_Ranking_Counter_Invoices_All_Brands.xlsx")
SERVICE_FILE_PATH = os.path.join(ROOT_FILE_PATH, r"Data&Files\Service JAN_Oct_Parts_Ranking_ROs_All_Brands.xlsx")
COUNTERPAD_FILE_PATH = os.path.join(ROOT_FILE_PATH, r"Data&Files\Counter_Pad_011425.xlsx")




## @ Variables ##

print_df_after_import = False
print_df_data_analyse = True

drop0Dims = False




## @ Parameters ##

## * Zoning Parameters
# TODO: Clarify for other Zones
totalDaysOfData = 300    # Total Days in Dataset
redHot1SaleTP = 1        # 1 Sell per 1 day
red1SaleTP =  7          # 1 sell per 7 days (1 week)   
orange1SaleTP = 14       # 1 sell per 14 days  (2 weeks) 
yellow1SaleTP = 21       # 1 sell per 21 days  (3 weeks)
green1SaleTP = 30        # 1 sell per 30 days  (1 month)
blue1SaleTP = float("inf")     # 1 sell per 300 Days (~Rest of Data)

zones = {
    'Red Hot': totalDaysOfData/redHot1SaleTP,
    'Red': totalDaysOfData/red1SaleTP,
    'Orange': totalDaysOfData/orange1SaleTP,
    'Yellow': totalDaysOfData/yellow1SaleTP,
    'Green': totalDaysOfData/green1SaleTP,
    'Blue': totalDaysOfData/blue1SaleTP
}


## * Storage Parameters
tirePercent = 0.5      ##  50% of tires are 33 inches, or more
fillFactor = 0.7       #  70% Filling, 30% Open Space for DRAWER / RACK / SHELVE




# Define categorization rules
categorizationRulesGM = [
    ['include', 'nut', 'Nuts'],
    ['include', 'washer', 'Washer'],
    ['include', 'bolt', 'Bolt'],
    ['include', 'pin', 'Pin'],
    ['include', 'lever', 'Transmission'],        
    ['include', 'andcable', 'Cable'],
    ['include', 'bearing', 'Bearings'],
    ['include', 'becu', 'Control Modules & ECUs'],
    ['include', 'lwr cont', 'Chassis'],
    ['include', 'upr cont', 'Chassis'],
    ['include', 'bushing', 'Chassis'],
    ['include', 'belt', 'Belts'],
    ['include', 'bolt', 'Bolts'],
    ['include', 'bowdencable', 'Cable'],
    ['include', 'brk', 'Brakes'],
    ['include', 'bumper', 'Body'],
    ['include', 'cable', 'Cable'],
    ['include', 's/str', 'Latch'],
    ['include', 'cabshaft', 'Cab Shafts'],
    ['include', 'pcv', 'PCV'],
    ['include', 'camshaft', 'Cam Shafts'],
    ['include', 'chain', 'Chains'],
    ['include', 'circlip', 'Clips'],
    ['include', 'clamp', 'Clamp'],
    ['include', 'clip', 'Clips'],
    ['include', 'countergear', 'Counter Gear'],
    ['include', 'countershaft', 'Counter Shafts'],
    ['include', 'cover', 'Covers'],
    ['include', 'crankshaft', 'Shafts'],
    ['include', 'crossmember', 'Chassis'],
    ['include', 'crosswire', 'Wiring'],
    ['include', 'daempferfilter', 'Air Filters'],
    ['include', 'defender', 'Body'],
    ['include', 'door', 'Doors'],
    ['include', 'duraseal', 'Seals'],
    ['include', 'eclipse', 'Clips & Retainers'],
    ['include', 'econoseal', 'Seals'],
    ['include', 'ecu', 'Control Modules & ECUs'],
    ['include', 'eyebolt', 'Eyebolt'],
    ['include', 'fan', 'Fan'],
    ['include', 'fastener', 'Fastener'],
    ['include', 'fender', 'Fender'],
    ['include', 'filter', 'Filters'],
    ['include', 'foam', 'Foam'],
    ['include', 'foglamp', 'Fog Lamp'],
    ['include', 'frame', 'Frames'],
    ['include', 'gasket', 'Gaskets'],
    ['include', 'gear', 'Gear'],
    ['include', 'hairspring', 'HAir Spring'],
    ['include', 'handle', 'Handle'],
    ['include', 'hdlamp', 'Head Lamp'],
    ['include', 'headlamp', 'Head Lamp'],
    ['include', 'hinge', 'Hinge'],
    ['include', 'hose', 'Hose'],
    ['include', 'insulator', 'Insulator'],
    ['include', 'intank', 'Intank'],
    ['include', 'jackscrew', 'Jack Screw'],
    ['include', 'lamp', 'Lamp'],
    ['include', 'latch', 'Latches'],
    ['include', 'latching', 'Latches'],
    ['include', 'light', 'Light'],
    ['include', 'mainshaft', 'Main Shaft'],
    ['include', 'module', 'Control Module'],
    ['include', 'motorcraft', 'Motorcraft'],
    ['include', 'motor', 'Motors'],
    ['include', 'motorcycle', 'Motorcycle'],
    ['include', 'motorola', 'Motors'],
    ['include', 'oilseal', 'Oil Seal'],
    ['include', 'outdoor', 'Outdoor'],
    ['include', 'overfender', 'Over Fender'],
    ['include', 'pinion', 'Pinion'],
    ['include', 'pipe', 'Pipes'],
    ['include', 'polyfoam', 'Ploy Foam'],
    ['include', 'propshaft', 'Prop Shaft'],
    ['include', 'pump', 'Pumps'],
    ['include', 'recovery', 'Others'],
    ['include', 'saddleclamp', 'Saddle Clamp'],
    ['include', 'scotseal', 'Scot Seals'],
    ['include', 'screw', 'Screw'],
    ['include', 'seal', 'Seals'],
    ['include', 'secu', 'Security ECU'],
    ['include', 'sensor', 'Sensors'],
    ['include', 'shaft', 'Shafts'],
    ['include', 'speedclip', 'Speed Clips'],
    ['include', 'spring', 'Springs'],
    ['include', 'steering', 'Steering'],
    ['include', 'strgpump', 'Storage Pump'],
    ['include', 'subframe', 'Sub Frames'],
    ['include', 'taillamp', 'Tail Lamp'],
    ['include', 'tarik', 'Fluid Storage'],
    ['include', 'tanks', 'Tanks'],
    ['include', 'unigear', 'Unigear'],
    ['include', 'unsealed', 'Unsealed'],
    ['include', 'valve', 'Valves'],
    ['include', 'axle', 'Axle'],
    ['include', 'cap', 'Cap'],
    ['include', 'decal', 'Hood'],
    ['include', 'hood', 'Hood'],
    ['include2', 'moulding', 'fascia', 'Moulding Fascia'],    
    ['include2', 'moulding', 'hdlp', 'Headlamp Moulding'],
    ['include2', 'moulding', 'body', 'Body Moulding'],    
    ['include2', 'moulding', 's/d', 'Sidedoor Moulding'],    
    ['include2', 'moulding', 'pnl', 'Panel Moulding'],   
    ['include2', 'moulding', 'fndr', 'Fender Moulding'],  
    ['include', 'mldg', 'Moulding'],       
    ['include', 'moulding', 'Moulding'],    
    ['include', 'bumper', 'bumper'],
    ['include', 'abs', 'Abs'],
    ['include', 'brake', 'Brakes'],
    ['include', 'bpr', 'Bumper'],
    ['include', 'a/c', 'AC'],
    ['include', 'vac', 'HVAC'],
    ['include', 'wrg', 'Wiring'],
    ['include', 'harness', 'Harness'],
    ['include', 'trim', 'Trims'],
    ['include', 'tire', 'Tires'],
    ['include', 'battery', 'Battery'],
    ['include', 'strut', 'Suspension'],
    ['include', 'stab', 'Suspension'],
    ['include2', 'shield', 'skid', 'Suspension'],
    ['include2', 'lugg', 'carr', 'Exterior'],
    ['include2', 'eng', 'indicator', 'Instrumentation'],
    ['include2', 'pmp', 'therm', 'Cooling'],
    ['include2', 'cv', 'cd', 'Media'],
    ['include', 'frame', 'Frame'],
    ['include', 'console', 'Console'],
    ['include', 'strg', 'Steering'],
    ['include', 'seat', 'Seats'],
    ['include', 'engine', 'Engine'],
    ['include', 'radiator', 'Radiator'],
    ['include', 'oil', 'Oil'],
    ['include', 'mirror', 'Mirrors'],
    ['include', 'paint', 'Paint'],
    ['include', 'cluster', 'Cluster'],
    ['include', 'wdo', 'Windows'],
    ['include', 'window', 'Windows'],
    ['include', 'radio', 'Radio'],
    ['include', 'generator', 'Generator'],
    ['include', 'spkr', 'Speaker'],
    ['include', 'reinforcement', 'Reinforcement'],
    ['include', 'windshield', 'Windshield'],
    ['include2', 'blade', 'wsw', 'Wiper'],
    ['include', 'wsw', 'Wiper'],
    ['include', 'wiper', 'Wiper'],
    ['include2', 'head', 'cyl', 'Cylinder Head'],
    ['include2', 'booster', 'p/b', 'Booster p/b'],
    ['include2', 'mount', 'eng', 'Mount Eng'],
    ['include2', 'tank', 'fuel', 'Fuel Tank'],
    ['include2', 'spark', 'plug', 'Spark Plug'],
    ['include2', 'transmitter', 'theft', 'Theft Transmitter'],
    ['include2', 'drv', 'shf', 'Drive Shaft'],
    ['include2', 'prop', 'shf', 'Prop Shaft'],
    ['include2', 'carrier', 'diff', 'Carrier Diff'],
    ['include2', 'starter', 'asm', 'Starter Asy'],
    ['include2', 'switch', 'ign', 'Switch Ignition'],
    ['include2', 'connector', 'harn', 'Connector Harn'],
    ['include2', 'panel', 'asm', 'Panel Asy'],
    ['include2', 'label', 'emis', 'Label Emission'],
    ['include2', 'tube', 'pcv', 'Tube Pcv'],
    ['include2', 'rear', 'mir', 'Rear Mirrors'],
    ['include2', 'front', 'mir', 'Front Mirrors'],
    ['include2', 'view', 'mir', 'Mirrors'],    
    ['include2', 'clu', 'press', 'Press Clutch'],
    ['include2', 'clu', 'cylinder', 'Clutch Cylinder'],
    ['include2', 'wheel', 'kit', 'Wheel Kit'],
    ['include', 'stereo', 'Audio'],
    ['include', 'armrest', 'Arm Rest'],
    ['include', 'panel-rf', 'Interior'],
    ['include', 'airbag', 'Airbag'],
    ['include', 'speaker', 'Speaker'],
    ['include2', 'rail', 'si', 'Rail Si'],
    ['include2', 'rail', 'pnl', 'Rail Panel'],
    ['include2', 'cleaner', 'air', 'Air Cleaner'],
    ['include2', 'manifold', 'int', 'Manifold Interior'],
    ['include2', 'thermostat', 'eng', 'Thermostat Engine'],
    ['include2', 'rod', 'conn', 'Connector Rod'],
    ['include2', 'liner', 'w/h', 'Liner Wheel'],
    ['include2', 'pad', 'tr', 'Interior'],
    ['include2', 'shield', 'w/h', 'Wheel Shield'],
    ['include2', 'plate', 'tr', 'Plate Tr'],
    ['include2', 'nut', 'whl', 'Wheels Nut'],
    ['include2', 'shield', 'air', 'Air Shield'],
    ['include2', 'shield', 'sph', 'Sph Shield'],
    ['include2', 'bat', 'cell', 'Battery Cell'],
    ['include', 'sunshade', 'Sunshade'],
    ['include', 'bezel', 'Bezel'],
    ['include', 'starter', 'Starter'],
    ['include', 'throttle', 'Throttle'],
    ['include', 'throtte', 'Throttle'],
    ['include', 'throttle', 'Throttle'],
    ['include2', 'bar', 'tie', 'Bar Tie'],
    ['include2', 'compartment', 'flr', 'Compartment Floor'],
    ['include2', 'panel', 'w/h', 'Wheel Panel'],
    ['include2', 'core', 'htr', 'Core Heater'],
    ['include2', 'outlet', 'air', 'Outlet Air'],
    ['include2', 'yoke', 'trans', 'Yoke Transmission'],
    ['include2', 'yoke', 'shf', 'Yoke Shaft'],
    ['include2', 'mount', 'trans', 'Mount Transmission'],
    ['include2', 'control', 'trns', 'Control Transmission'],
    ['include2', 'switch', 'park', 'Parking Switch'],
    ['include2', 'yoke', 'susp', 'Yoke Suspension'],
    ['include2', 'yoke', 'prop', 'Yoke Propeller'],
    ['include2', 'yoke', 'diff', 'Yoke Differential'],
    ['include2', 'yoke', 'slip', 'Yoke Slip'],
    ['include2', 'housing', 'axl', 'Axle Housing'],
    ['include2', 'ring', 'pstn', 'Ring Piston'],
    ['include2', 'balancer', 'shf', 'Shaft Balancer'],
    ['include2', 'air', 'inl', 'Air Inlet'],
    ['include2', 'deflector', 'wat', 'Water Deflector'],
    ['include2', 'panel', 'body', 'Panel Body'],
    ['include2', 'hub', 'asm', 'Hub Asy'],
    ['include2', 'hub', 'assem', 'Hub Asy'],
    ['include2', 'stud', 'whl', 'Wheel Stud'],
    ['include2', 'converter', 'exh', 'Exhaust Converter'],
    ['include', 'manifold', 'exh', 'Manifold Exhaust'],
    ['include2', 'converter', 'torq', 'Converter Torque'],
    ['include2', 'lock', 'asm', 'Lock Asy'],
    ['include2', 'canister', 'emis', 'Canister Emissions'],
    ['include2', 'tube', 'emis', 'Tube Emissions'],
    ['include2', 'outlet', 'wat', 'Water Outlet'],
    ['include2', 'grille', 'asm', 'Grille Asy'],
    ['include2', 'case', 'asm', 'Case Asy'],
    ['include2', 'indicator', 'trans', 'Transmission Indicator'],
    ['include2', 'support', 'trans', 'Transmission Support'],
    ['include2', 'indicator', 'trns', 'Transmission Indicator'],        
    ['include2', 'clu', 'mas', 'Clutch Master'],
    ['include2', 'air', 'inl', 'Air Inlet'],
    ['include2', 'support', 'rad', 'Radiator Support'],
    ['include2', 'grille', 'rad', 'Radiator Grille'],
    ['include2', 'tank', 'rad', 'Radiator Tank'],
    ['include2', 'injector', 'fuel', 'Fuel Injector'],
    ['include2', 'gate', 'lift', 'Lift Gate'],
    ['include2', 'gate', 'tail', 'Tail Gate'],
    ['include2', 'sender', 'fuel', 'Fuel Sender'],
    ['include2', 'htr', 'cool', 'Cool Heater'],
    ['include2', 'panel', 'otr', 'Panel Other'],
    ['include2', 'key', 'lk', 'Key Lock'],
    ['include2', 'bat', 'tray', 'Battery Tray'],
    ['include2', 'link', 'chk', 'Check Link'],
    ['include2', 'rod', 'lk', 'Rod Lock'],
    ['include2', 'step', 'asm', 'Step Asy'],
    ['include2', 'head', 'speedo', 'Head Speedometer'],
    ['include2', 'shield', 'noise', 'Shield Noise'],
    ['include', 'transmission', 'Transmission'],
    ['include', 'differential', 'Differential'],
    ['include', 'carpet', 'Carpet'],
    ['include', 'connector', 'Connector'],
    ['include', 'voltage', 'Voltage'],
    ['include', 'transmitter', 'Transmitter'],
    ['include', 'eprom', 'Eprom'],
    ['include', 'regulator', 'Regulator'],
    ['include', 'lifter', 'Lifter'],
    ['include', 'manifold', 'Manifold'],
    ['include', 'bracket', 'Bracket'],
    ['include', 'piston', 'Piston'],
    ['include', 'solv', 'Solvent'],
    ['include', 'compressor', 'Compressor'],
    ['include', 'evaporator', 'Evaporator'],
    ['include', 'duct', 'Duct'],
    ['include', 'htr', 'Heater'],
    ['include', 'gusset', 'Gusset'],        
    ['include', 'navn', 'Navigation'],
    ['include', 'muffler', 'Muffler'],
    ['include', 'bulb', 'Bulb'],
    ['include', 'defletor', 'Deflector'],
    ['include', 'switch', 'Switch'],
    ['include', 'charger', 'Charger'],
    ['include', 'rotor', 'Rotor'],
    ['include', 'fuse', 'Fuse'],
    ['include', 'chrg', 'Charger'],
    ['include', 'boot', 'Boot'],
    ['include', 'shim', 'Shim'],
    ['include', 'radiator', 'Radiator'],
    ['include', 'clutch', 'Clutch'],
    ['include', 'mat', 'Mat'],
    ['include', 'display', 'Display'],
    ['include', 'antenna', 'Antenna'],
    ['include', 'relay', 'Relay'],
    ['include', 'camera', 'Camera'],
    ['include', 'amplifier', 'Amplifier'],
    ['include', 'retainer', 'Retainer'],
    ['include', 'manual', 'Manual'],
    ['include', 'gasket', 'Gasket'],
    ['include', 'susp', 'Suspension'],
    ['include', 'spacer', 'Spacer'],
    ['include', 'molding', 'Molding'],
    ['include', 'emblem', 'Emblem'],
    ['include', 'wheel', 'Wheel'],
    ['include', 'pinion', 'Pinion'],
    ['include', 'lock', 'Lock'],
    ['include', 'pedal', 'Pedal'],
    ['include', 'jack', 'Jack'],
    ['include', 'baffle', 'Baffle'],
    ['include', 'cooler', 'Cooler'],
    ['include', 'weatherstrip', 'Weatherstrip'],
    ['include', 'panel', 'Panel'],
    ['include', 'wire', 'Wire'],
    ['include', 'lid', 'Lid'],
    ['include', 'box', 'Box'],
    ['include', 'i/p', 'Instr Panel'],
    ['include', 'cvr', 'Cover'],
    ['include', 'body', 'Body'],
    ['include', 'applique', 'Applique'],
    ['include2', 'sun', 'r', 'Sun Roof'],        
    ['include2', 'shield', 'ht', 'Shield Heater'],        
    ['include2', 'rail', 'asm', 'Rail Asy'],
    ['include2', 'shield', 'sight', 'Shield Sight'],
    ['include2', 'trans', 'fluid', 'Trans Fluid'],
    ['include2', 'converter', 'ctltc', 'Converter Ctltc'],
    ['include2', 'arm', 'vlv', 'Arm Valve'],        
    ['include', 'bolster', 'Bolster'],
    ['include', 'gate', 'Gate'],
    ['include', 'f/tnk', 'Fuel Tank'],
    ['include', 'hoist', 'Hoist'],
    ['include', 'rod', 'Rods'],
    ['include', 'prom', 'Prom'],
    ['include', 'receiver', 'Receiver'],
    ['include', 'transceiver', 'Transceiver'],
    ['include', 'brace', 'Brace'],
    ['include', 'cyl', 'Cylinder'],
    ['include', 'plug', 'Plug'],
    ['include', 'adjust kit', 'Adjustment Kit'],
    ['include', 'stud', 'Stud'],
    ['include', 'housing', 'Housing'],
    ['include', 'resistor', 'Resistor'],
    ['include', 'base', 'Base'],
    ['include', 'lens', 'Lens'],
    ['include', 'carrier', 'Carrier'],
    ['include', 'blower', 'Blower'],
    ['include', 'terminal', 'Terminal'],
    ['include', 'bar', 'Bars'],
    ['include', 'pkg', 'Package'],
    ['include', 'nozzle', 'Nozzle'],
    ['include', 'knob', 'Knob'],
    ['include', 'restraint', 'Restraint'],
    ['include', 'grille', 'Grille'],
    ['include', 'distributor', 'Distributor'],
    ['include', 'pole piece', 'Pole Piece'],
    ['include', 'accumulator', 'Accumulator'],
    ['include', 'cloth', 'Cloth'],
    ['include', 'solenoid', 'Solenoid'],
    ['include', 'drive', 'Drive'],
    ['include', 'contact', 'Contact'],
    ['include', 'member', 'Member'],
    ['include', 'closeout', 'Closeout'],
    ['include', 'hdl ', 'Handle'],
    ['include2', 'hdlp', 'hsg', 'Headlamp Housing'],
    ['include', 'hub', 'Hub'],
    ['include', 'platform', 'Platform'],
    ['include', 'layout', 'Layout'],
    ['include', 'horn', 'Horn'],
    ['include', 'reservoir', 'Reservoir'],
    ['include', 'filler', 'Filler'],
    ['include', 'alternator', 'Alternator'],
    ['include', 'pulley', 'Pulley'],
    ['include', 'rail', 'Rail'],
    ['include', 'power carb kit', 'Power Carb Kit'],
    ['include', 'rectifier', 'Rectifier'],
    ['include', 'pan', 'Pan'],
    ['include', 'extension', 'Extension'],
    ['include', 'player', 'Player'],
    ['include', 'bow', 'Bow'],
    ['include', 'cbl ', 'Cable'],        
    ['include', 'holder', 'Holder'],
    ['include', 'brush', 'Brush'],
    ['include', 'hanger', 'Hanger'],
    ['include', 'actuator', 'Actuators'],
    ['include', 'carton', 'Carton'],
    ['include', 'tire', 'Tire'],
    ['include', 'grommet', 'Grommets'],
    ['include', 'cab', 'Cabin'],
    ['include', 'tube', 'Tubes'],
    ['include', 'refill', 'Refill'],
    ['include', 'tank', 'Tank'],
    ['include', 'pin', 'Pins'],
    ['include', 'radial', 'Radial'],
    ['include', 'breather', 'Breather'],
    ['include', 'label', 'Labels'],
    ['include', 'tubing', 'Tubing'],
    ['include', 'cleaning', 'Cleaner'],
    ['include', 'plt', 'Plate'],
    ['include', 'stiffener', 'Stiffener'],
    ['include', 'coolant', 'Coolant'],
    ['include', 'pushbutton', 'Push Button'],
    ['include', 'protector', 'Protector'],
    ['include', 'tuning kit', 'Tuning Kit'],
    ['include', 'sprocket', 'Sprocket'],
    ['include', 'net', 'Net'],
    ['include', 'breaker', 'Breaker'],
    ['include2', 'check', 's/d', 'Check Side Door'],
    ['include', 'attachment kit', 'Attachment Kit'],
    ['include', 'insert', 'Inserts'],
    ['include', 'installation kit', 'Installation Kit'],
    ['include', 'case', 'Cases'],
    ['include', 'strap', 'Straps'],
    ['include', 'heater', 'Heating'],
    ['include', 'vent', 'Vents'],
    ['include', 'rivet', 'Rivet'],
    ['include', 'leaf', 'Leaf'],
    ['include', 'impeller', 'IMpeller'],
    ['include', 'striker', 'Striker'],
    ['include', 'arm,vlv rkr', 'Rocker Valve Arm'],
    ['include', 'rack', 'Rack'],
    ['include', 'recorder', 'Recorder'],
    ['include', 'pad', 'Pad'],
    ['include', 'joint', 'Joints'],
    ['include', 'sleeve', 'Sleeves'],
    ['include', 'collar', 'Collars'],
    ['include', 'speedo', 'Speedometer'],
    ['include', 'alarm', 'Alarm'],
    ['include', 'key', 'Keys'],
    ['include', 'flap', 'Flap'],
    ['include', 'drag link', 'Drag Link'],
    ['include', 'Adjuster', 'Adjuster'],
    ['include', 'shackle', 'Shackle'],
    ['include', 'axl', 'Axle'],
    ['include', 'container', 'Container'],
    ['include', 'twc converter', 'Twc Converter'],
    ['include', 'finisher', 'Finisher'],
    ['include', 'dryer', 'Dryer'],
    ['include', 'governor', 'Governor'],
    ['include', 'catalog', 'Catalog'],
    ['include', 'glass', 'Glass'],
    ['include', 'compartment', 'Compartment'], 
    ['include', 'grease', 'Grease'],
    ['include', 'fork', 'Fork'],
    ['include', 'cleaner', 'Cleaners'],
    ['include', 'cam', 'CAM'],
    ['include', 'gls', 'Glass'],
    ['include', 'transistor', 'TRansistor'],
    ['include', 'strainer', 'Strainer'],
    ['include', 'sill', 'Sill'],
    ['include', 'speedometer', 'Speedometer'],
    ['include', 'but asm', 'Buttons Asy'],
    ['include', 'flare', 'Flare'],
    ['include', 'carburetor', 'Carburetor'],
    ['include', 'film', 'Films'],
    ['include', 'monitor', 'Monitor'],
    ['include', 'montr', 'Monitor'],        
    ['include', 'bag', 'Bag'],
    ['include', 'rim', 'Rim'],
    ['include', 'timer', 'Timer'],
    ['include', 'silencer', 'Silencer'],
    ['include', 'tool kit', 'Tool Kit'],
    ['include', 'circuit board', 'Circuit Board'],
    ['include', 'sunshade', 'Sunshade'],
    ['include2', 'shade', 'lugg', 'Luggage Shade'],
    ['include', 'wedge', 'Wedge'],
    ['include', 'calibrator', 'Calibrator'],
    ['include', 'resonator', 'Resonator'],
    ['include', 'divider', 'Divider'],
    ['include', 'core,rad', 'Radiator Core'],
    ['include2', 'guide,vlv', 'lftr', 'Guide Valve Lifter'],
    ['include', 'guide,vlv', 'Guide Valve'],
    ['include2', 'o ring', 'seal-fuel', 'O Ring Seal Fuel'],
    ['include2', 'o ring', 'a/c', 'O Ring Seal A/C'],
    ['include2', 'o ring', 'trans', 'O Ring Seal Transmission'],
    ['include2', 'o-ring', 'drv', 'O Ring Seal Drive'],
 #   ['include', 'pocket', 'Pocket'],    GEAR SET,DIFF RING & DRV
    ['include', 'safety kit', 'Safety Kit'],
    ['include', 'ring,input shf rr brg thr', 'Input Shaft Ring Bearing'],
    ['include', 'ballast kit,hdlp', 'Ballast Kit Headlamp'],
    ['include2', 'gear set', 'diff ring', 'Ring Gear Diff Set'],
    ['include', 'tray', 'Tray'],
    ['include', 'printed circuit', 'Printed Circuit'],
    ['include', 'guard', 'Guard'],
    ['include', 'synchronizer', 'SYnchronizer'],
    ['include', 'weight', 'Weight'],
    ['include', 'controller', 'Controller'],
    ['include', 'adapter', 'Adapters'],
    ['include2', 'pawl', 's/d', 'Side Door Pawl'],
    ['include2', 'pawl', 'gate', 'Gate Pawl'],    
    ['include2', 'pawl', 'seat', 'Seat Pawl'],
    ['include2', 'pawl', 'bumper', 'Bumper Pawl'],
    ['include2', 'pawl', 'bolt', 'Bolt Pawl'],
    ['include', 'nut,s/knu', 'Steer Knuckke Nut'],
    ['include2', 'luggage', 'carrier', 'Luggage Carrier'],
    ['include2', 'gage', 'oil', 'Oil Gauge'],
    ['include2', 'gage', 'fuel', 'Fuel Gauge'],
    ['include2', 'gage', 'temp', 'Temperature Gauge'],
    ['include2', 'gage', 'combo', 'Combo Gauge'],
    ['include2', 'gage', 'boos', 'Boost Gauge'],
    ['include', 'hook', 'Hooks'],
    ['include2', 'telltale', 'info ctr', 'Info Center Telltale'],
    ['include2', 'telltale', 'inst cstr', 'Instrument Cluster Telltale'],
    ['include2', 'telltale', 'instr', 'Instrument Telltale'],
    ['include', 'pillar', 'Pillar'],
    ['include', 'mount', 'Mounts'],
    ['include', 'canister', 'Canister'],
    ['include', 'deadener', 'Deadener Material'],
    ['include', 'cushion', 'Cushion'],
    ['include3', 'stripe', 'flare', 'flame', 'Flare Stripe Flame'],
    ['include2', 'stripe', 'r/cmpt', 'Rear Comp Stripe'],
    ['include3', 'stripe', 'hood', 'ctr', 'Center Hood Stripe'],
    ['include2', 'stripe', 'body', 'Body Stripe'],
    ['include3', 'stripe', 'flr', 'cnsl', 'Floor Console Stripe'],
    ['include2', 'loop', 'clamp', 'Clamp Loop'],
    ['include3', 'loop', 'child', 'Child Seat Loop'],
    ['include3', 'loop', 'plate', 'cargo', 'Plate Cargo Loop'],
    ['include2', 'loop', 'cargo', 'Cargo Loop'],
    ['include2', 'loop', 'belt guide', 'Belt Guide Loop'],
    ['include', 'loop', 'Loop'],
    ['include2', 'card', 'Navn data', 'Electronics'],
    ['include2', 'card', 'field', 'Field Comm Card'],
    ['include2', 'card', 'business', 'Business Card'],
    ['include2', 'card', 'toll', 'Toll Card Holder'],
    ['include2', 'card', 'reader', 'Card Reader'],
    ['include3', 'screen', 'hood', 'air', 'Hood Air Screen'],
    ['include3', 'screen', 'air', 'inl', 'Air Inlet Screen'],
    ['include2', 'screen', 'winterfront', 'Winterfront Screen'],
    ['include2', 'screen', 'grl', 'Grille Screen'],
    ['include2', 'screen', 'spkr', 'Speaker Screen'],
    ['include2', 'flasher', 'emer', 'Emergency Flasher'],
    ['include3', 'flasher', 'hazard', 'sig', 'Hazard Signal Flasher'],
    ['include2', 'flasher', 'hazard', 'Hazard Flasher'],
    ['include', 'flasher', 'Flasher'],
#    ['include', 'cup', 'Interior'],
#    ['include', 'fdtm', 'Fdtm'],
    ['include2', 'slat', 'lugg car', 'Luggage Slat'],
    ['include2', 'slat', '', 'Interior'],
    ['include', 'inslator', 'Insulator'],
    ['include', 'receptacle', 'Receptacle'],
    ['include2', 'link', 'adj', 'Adjustment Link'],
    ['include2', 'link', 'tie', 'Link Tie'],
    ['include2', 'link', 'bolt', 'Bolt Link'],
    ['include2', 'link', 'bracket', 'Bracket Link'],
    ['include2', 'link', 'bushing', 'Bushing Link'],
    ['include', 'link', 'Link'],
    ['include', 'stator', 'Stator'],
    ['include', 'decor strip', 'Decoration Strip'],
    ['include2', 'absorber', 'shk', 'Shock Absorber'],
    ['include2', 'link', 'rod,strg', 'Steering Rod Linkage'],
    ['include2', 'horn', 'asm', 'Horn Asy'],
    ['include2', 'seal kit', 'pinion', 'Pinionn Seal Kit'],
    ['include2', 'retainer', 'pad', 'Retainer Pad'],
    ['include2', 'horn', 'asm', 'Horn Asy'],
    ['include', 'cap,', 'Cap'],
    ['include', 'cap ', 'Cap'],
    ['include', 'washer', 'Washer'],
    ['include', 'printed circuit', 'Electronics'],
    ['include', 'pnl-qtr otr', 'Outer Panel Qtr'],
    ['include2', 'deflector', 'air', 'Air Deflector'],
    ['include2', 'plate', 'sw', 'Interior'],
    ['include2', 'indicator', 'trns', 'Transmission Indicator'],
    ['include2', 'plate', 'clu', 'Plate Clutch'],
    ['include', 'footrest', 'Foot Rest'],
    ['include', 'microphone', 'Microphone'],
    ['include', 'control', 'Controls'],
    ['include', 'escutcheon', 'Escutcheon'],
    ['include', 'p & a price list (comm)', 'Price List (comm)'],
    ['include', 'ballast', 'Ballast'],
    ['include', 'repair kit', 'Repair Kit'],
    ['include', 'cradle', 'Cradle'],
    ['include', 'headphone', 'Head phone'],
    ['include', 'cage', 'Cage'],
    ['include', 'disc', 'Disc'],
    ['include', 'ball', 'Ball'],
    ['include', 'nut-push in', 'Nut Push In'],
    ['include', 'ornament', 'Ornament'],
    ['include', 'fluid', 'Fluid'],
    ['include', 'float kit,carb', 'Float Kit Carb'],
    ['include2', 'plate', 'drvn', 'Plate Drive'],        
    ['include2', 'arm', 'pit', 'Arm Pit'],    
    ['include2', 'wrench', 'whl', 'Wheel Wrench'],   
    ['include2', 'ring', 'ret', 'Ring Retainer'],   
    ['include2', 'diff', 'drv', 'Differential Drive'],  
    ['include2', 'shield', 'eng', 'Shield Engine'],  
    ['include2', 'support', 'sh met', 'Support Sh Metal'],  
    ['include2', 'servo', 'asm', 'Servo Asy'], 
    ['include2', 'lk', 'asm', 'Lock Asy'], 
    ['include2', 'rad', 'drn', 'Radiator Drain'],  
    ['include2', 'mir', 'asm', 'Mirror Asy'], 
    ['include2', 'flange', 'clu', 'Flange Clutch'],          
    ['include2', 'inlet', 'wat', 'Water Inlet'],     
    ['include2', 'pivot', 'hdl', 'Pivot Handle'],     
    ['include2', 'meter', 'fuel', 'Fuel Meter'], 
    ['include2', 'cool', 'air', 'Air Cooler'],     
    ['include2', 'evap', 'core', 'Evaporator Core'],    
    ['include2', 'knock', 'sen', 'Knock Sensor'],     
    ['include2', 'conversion', 'vlv', 'Conversion Valve'],  
    ['include2', 'diff', 'brg', 'Differential Bearing'],      
    ['include2', 'booster', 'audio', 'Booster Audio'],  
    ['include2', 'service', 'audio', 'Service Audio'],            
    ['include', 'detent', 'Detent'],     
    ['include', 'lining', 'Lining'],        
    ['include', ' rad', 'Radiator'],      
    ['include', 'fascia', 'Fascia'],    
    ['include', 'circuit', 'Circuit'],   
    ['include', 'diode', 'Diode'],                                               
    ['include', 'lubricant', 'Lubricant'],  
    ['include', 'harn asm', 'Harness Asy'],
    ['include', 'plate', 'Plate'],
    ['include', 'condenser', 'Condenser'],
    ['include', 'gauge', 'Gauge'],
    ['include', 'thermostat', 'Thermostat'],
    ['include', 'overhaul', 'Overhaul'],
    ['include', 'coupling', 'Coupling'],
    ['include', 'plate', 'Plate'],
    ['include', 'socket', 'Socket'],
    ['include', 'shft', 'Shaft'],
    ['include', 'hdlp', 'Head Lamp'],
    ['include', 'sensing', 'Sensors'],
    ['include', 'buckle', 'Buckle'],
    ['include', 'flange', 'Flange'],
    ['include', 'hge', 'Hinge'],        
    ['include', 'drum', 'Drum'],
    ['include', 'tow', 'Towing'],
    ['include', 'wrench', 'Wrench'],
    ['include', 'channel', 'Channel'],
    ['include', 'calibration', 'calibration'],
    ['include', 'a/rst', 'Armrest'],
    ['include', 'damper', 'Damper'],
    ['include', 'converter', 'Converter'],        
    ['include', 'shft', 'Shaft'],   
    ['include', 'rotator', 'Rotator'],   
    ['include', 'tuning', 'Tuning Kit'],  
    ['include', 'jumper', 'Jumper'],         
    ['include', 'panel asm', 'Panel Asy'],        
    ['include', 'pnl asm', 'Panel Asy'],
    ['include', 'support', 'Support'],
    ['include', 'clu ', 'Clutch'],
    ['include', 'parking', 'Parking'],    
    ['include', 'roller', 'Roller'],     
    ['include', 'balancer', 'Balancer'], 
    ['include', 'tachometer', 'Tachometer'], 
    ['include', 'deflector', 'Deflector'],  
    ['include', 'reflector', 'Reflector'],    
    ['include', 'pivot', 'Pivot'], 
    ['include', 'tape', 'Tape'],         
    ['include', 'ring', 'Ring'],  
    ['include', 'marketing', 'Marketing'],  
    ['include', 'pnl', 'Panel'],   
    ['include', 'dampener', 'Dampener'],  
    ['include', 'odometer', 'Speedometer'],  
    ['include', 'adhesive', 'Tape'],  
    ['include', 'shutter', 'Shutter'],  
    ['include', 'knuckle', 'Knuckle'],  
    ['include', 'shield', 'Shield'],  
    ['include', 'decor', 'Decor'],          
    ['include', 'nipple', 'Nipple'], 
    ['include', 'exh ', 'Exhaust'], 
    ['include', 'step', 'Exterior'],
    ['include', 'liner', 'Engine'],
    ['include', 'scoop', 'Body']
]
